language: elixir
elixir:
  - 1.13
otp_release:
  - 20.0
matrix:
  include:
    - elixir: 1.13
      otp_release: 24.0
env:
  - MIX_ENV=test
script:
  - mix dialyzer
  - mix coveralls.travis
  - mix credo --strict
  - mix test
