language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 20.0
matrix:
  include:
    - elixir: 1.7
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 21.0
env:
  - MIX_ENV=test
script:
  - mix dialyzer
  - mix coveralls.travis
  - mix credo --strict
  - mix test
